### Login
POST http://127.0.0.1:8000/api/v1/auth/login
Accept: application/json
Content-Type: application/json

{
    "email": "grace@mail.com",
    "password": "12345678"

}

### Perfil
GET http://127.0.0.1:8000/api/v1/auth/profile
Accept: application/json
Authorization: Bearer 5|bczSHGRs8im0tE1AioQpU1WhMmb0Z6gBoAy5vtfle0bdadfb


### Salir
POST http://127.0.0.1:8000/api/v1/auth/logout
Accept: application/json
Authorization: Bearer 5|bczSHGRs8im0tE1AioQpU1WhMmb0Z6gBoAy5vtfle0bdadfb