POST http://127.0.0.1:8000/api/pedido
Accept: application/json
Content-Type: application/json
Authorization: Bearer 15|4NRIknJreqjEUaZxAeLdT951MbSdVqbu9Eh4a4lo1843718b

{
    "cliente_id" : 2,
    "productos": [
        {"id":7, "cantidad":3},
        {"id":6, "cantidad":4}
    ]
}