GET http://127.0.0.1:8000/api/producto?page=1&limit=10&q=
Accept: application/json
Authorization: Bearer 15|4NRIknJreqjEUaZxAeLdT951MbSdVqbu9Eh4a4lo1843718b

### Guardar
POST  http://127.0.0.1:8000/api/producto
Accept: application/json
Authorization: Bearer 15|4NRIknJreqjEUaZxAeLdT951MbSdVqbu9Eh4a4lo1843718b
Content-Type: application/json

{
    "nombre": "Aire Acondicionado",
    "stock": 8,
    "precio": 200,
    "descripcion": "Aire Acondicionado",
    "categoria_id": 3

}

### Mostrar
GET http://127.0.0.1:8000/api/producto/1
Accept: application/json
Authorization: Bearer 15|4NRIknJreqjEUaZxAeLdT951MbSdVqbu9Eh4a4lo1843718b