GET http://127.0.0.1:8000/api/user

### Guardar

POST http://127.0.0.1:8000/api/user
Accept: application/json
Content-Type: application/json

{
    "name": "grace",
    "email": "grace@mail.com",
    "password": "12345678"

}

### Mostrar
GET http://127.0.0.1:8000/api/user/2
Accept: application/json

### Modificar

PUT http://127.0.0.1:8000/api/user/2
Accept: application/json
Content-Type: application/json

{
  "name": "steven",
  "email": "steven.update@mail.com",
  "password": "123456"
}

### Eliminar

DELETE http://127.0.0.1:8000/api/user/2